# Generated by Django 5.1.4 on 2025-01-07 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_app', '0004_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_days', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('bidding_end_date', models.DateField()),
                ('trip_type', models.CharField(choices=[('honeymoon', 'Honeymoon'), ('adventure', 'Adventure'), ('winter', 'Winter')], max_length=20)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancellation_policy', models.BooleanField(default=True)),
                ('itinerary_flexibility', models.BooleanField(default=True)),
                ('included_services', models.TextField()),
                ('excluded_services', models.TextField()),
                ('package_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('inprogress', 'In Progress')], default='inactive', max_length=20)),
                ('is_deleted', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_agency_id', to='common_app.user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_provider_id', to='common_app.user')),
            ],
            options={
                'db_table': 'tour_package',
            },
        ),
    ]
