# Generated by Django 5.1.4 on 2025-01-10 07:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_provider', '0002_alter_tourpackage_travel_agency_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyItinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('itinerary_day', models.IntegerField(blank=True, null=True)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('travel_mode', models.CharField(blank=True, choices=[('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight'), ('boat', 'Boat')], max_length=10, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_package_id', to='package_provider.tourpackage')),
            ],
            options={
                'db_table': 'daily_itinerary',
            },
        ),
    ]
