# Generated by Django 5.1.4 on 2025-01-17 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0017_vehicletype'),
        ('package_provider', '0006_delete_tourpackagenecessity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackageNecessity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('decided_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seating_capacity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour_package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_package_id', to='package_provider.tourpackage')),
                ('vehicle_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_id', to='common_app.vehicletype')),
            ],
            options={
                'db_table': 'tour_package_necessitie',
            },
        ),
    ]
