# Generated by Django 5.1.4 on 2025-01-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0022_rename_tourpackagebid_bidproposal_and_more'),
        ('package_provider', '0007_tourpackagenecessity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourPackageNecessity',
            new_name='TourPackageBid',
        ),
        migrations.AlterModelTable(
            name='tourpackagebid',
            table='tour_package_bid',
        ),
    ]
