# Generated by Django 5.1.4 on 2025-01-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0024_remove_bidproposal_bid_status'),
        ('package_provider', '0008_rename_tourpackagenecessity_tourpackagebid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackagebid',
            name='approved_proposal_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackagebid',
            name='bid_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('bidded', 'Bidded'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='tourpackagebid',
            name='proposal_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackagebid',
            name='tour_package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_bids', to='package_provider.tourpackage'),
        ),
        migrations.AlterField(
            model_name='tourpackagebid',
            name='vehicle_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_bids', to='common_app.vehicletype'),
        ),
    ]
