# Generated by Django 5.1.4 on 2025-01-08 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_app', '0004_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_phone_no', models.CharField(max_length=15, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('vehicle_identity_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('four_wheel', 'Four Wheel'), ('two_wheel', 'Two Wheel')], default='four_wheel', max_length=10)),
                ('vehicle_category', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('gas', 'Gas')], max_length=10, null=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_start_date', models.DateField(blank=True, null=True)),
                ('insurance_end_date', models.DateField(blank=True, null=True)),
                ('insurance_coverage_details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_user_id', to='common_app.user')),
            ],
            options={
                'db_table': 'transport_vehicle',
            },
        ),
    ]
