# Generated by Django 5.1.4 on 2025-01-06 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('experience_years', models.FloatField()),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_type', models.CharField(choices=[('two_wheeler', 'Two-Wheeler'), ('commercial', 'Commercial'), ('heavy_vehicle', 'Heavy Vehicle')], max_length=20, null=True)),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiration_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_no', models.CharField(max_length=15)),
                ('is_deleted', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
    ]
