# Generated by Django 5.1.4 on 2024-12-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0002_oauthapplication_oauthaccesstoken_oauthrefreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthaccesstoken',
            name='application',
        ),
        migrations.RemoveField(
            model_name='oauthaccesstoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='oauthrefreshtoken',
            name='access_token',
        ),
        migrations.DeleteModel(
            name='OAuthApplication',
        ),
        migrations.DeleteModel(
            name='OAuthAccessToken',
        ),
        migrations.DeleteModel(
            name='OAuthRefreshToken',
        ),
    ]
