# Generated by Django 5.1.4 on 2024-12-30 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0003_remove_oauthaccesstoken_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('redirect_uri', models.URLField()),
            ],
            options={
                'db_table': 'oauth_application',
            },
        ),
        migrations.CreateModel(
            name='OAuthAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, unique=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_type', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.user')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.oauthapplication')),
            ],
            options={
                'db_table': 'oauth_access_token',
            },
        ),
    ]
