# Generated by Django 5.1.4 on 2024-12-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccesstoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-30 12:14:50.341478+05:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauthaccesstoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oauthapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-30 10:40:29.443183+05:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauthapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
