# Generated by Django 5.1.4 on 2025-01-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0005_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_created_by', to='common_app.user'),
        ),
        migrations.AddField(
            model_name='permission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_updated_by', to='common_app.user'),
        ),
    ]
