# Generated by Django 5.1.4 on 2025-01-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0006_permission_created_by_permission_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='created_by',
            field=models.ForeignKey(default='ede27776-9249-471c-b272-10680d3df2d0', on_delete=django.db.models.deletion.CASCADE, related_name='permission_created_by', to='common_app.user'),
            preserve_default=False,
        ),
    ]
