# Generated by Django 5.1.4 on 2025-01-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0008_alter_permission_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_updated_by', to='common_app.user'),
        ),
    ]
