# Generated by Django 5.1.4 on 2025-01-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0010_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_by_permissions', to='common_app.user'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='common_app.user'),
        ),
    ]
