# Generated by Django 5.1.4 on 2025-01-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0013_vehicletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
