# Generated by Django 5.1.4 on 2025-01-17 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0014_alter_vehicletype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
