# Generated by Django 5.1.4 on 2025-01-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0017_vehicletype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackagebid',
            old_name='additional_info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tourpackagebid',
            old_name='tour_package_id',
            new_name='package_necessities_id',
        ),
        migrations.RenameField(
            model_name='tourpackagebid',
            old_name='transport_vehicle_id',
            new_name='travel_agency_id',
        ),
        migrations.AlterField(
            model_name='tourpackagebid',
            name='bid_status',
            field=models.CharField(choices=[('pending', 'pending'), ('bidded', 'bidded'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='bidded', max_length=15),
        ),
    ]
