# Generated by Django 5.1.4 on 2025-01-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0018_rename_additional_info_tourpackagebid_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
