# Generated by Django 5.1.4 on 2025-01-21 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0019_remove_permission_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_status', models.CharField(choices=[('pending', 'pending'), ('bidded', 'bidded'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_id', to='common_app.tourpackagebid')),
                ('travel_agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_agency', to='common_app.user')),
            ],
            options={
                'db_table': 'bid_proposal',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_id', to='common_app.permission')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_id', to='common_app.role')),
            ],
            options={
                'db_table': 'role_permission',
            },
        ),
    ]
