# Generated by Django 5.1.4 on 2025-01-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0020_bidproposal_rolepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BidProposal',
        ),
    ]
