# Generated by Django 5.1.4 on 2025-01-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0021_delete_bidproposal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourPackageBid',
            new_name='BidProposal',
        ),
        migrations.AlterModelTable(
            name='bidproposal',
            table='bid_proposal',
        ),
    ]
