# Generated by Django 5.1.4 on 2025-01-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0022_rename_tourpackagebid_bidproposal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidproposal',
            old_name='package_necessities_id',
            new_name='bid_id',
        ),
    ]
